model = "prod_sigmoid_pooling"

[[block]]
block_type = "KmerMultipleEmbedding"
input_channel = 65
output_channel = 2
num_neighboring_features = 1

[[block]]
block_type = "ConcatenateFeatures"

[[block]]
block_type = "Linear"
input_channel = 15
output_channel = 150
activation = "relu"
batch_norm = true
n_reads_per_site = 50

[[block]]
block_type = "Linear"
input_channel = 150
output_channel = 32
activation = "relu"
batch_norm = false
n_reads_per_site = 50

[[block]]
block_type = "SigmoidProdPooling"
input_channel = 32
n_reads_per_site = 50
